# Generated by Django 2.0.2 on 2018-04-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='Photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('begin_time', models.DateField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('duration', models.IntegerField(default=1)),
                ('person', models.ManyToManyField(blank=True, related_name='record_person', to='map.Person')),
            ],
            options={
                'db_table': 'Record',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_record', to='map.Record'),
        ),
    ]
