# Generated by Django 2.0.3 on 2018-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='begin_time',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='records',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='records',
            name='photos',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
