# Generated by Django 2.0.3 on 2018-03-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180318_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='records',
            new_name='Record',
        ),
        migrations.AlterModelTable(
            name='record',
            table='Record',
        ),
    ]
