# Generated by Django 2.0.3 on 2018-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20180322_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='photos',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
