# Generated by Django 2.0.3 on 2018-04-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20180326_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
