# Generated by Django 2.0.3 on 2018-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20180403_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='photos',
            field=models.ImageField(upload_to='Photo/'),
        ),
    ]
