# Generated by Django 2.0.3 on 2018-04-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20180403_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='person',
        ),
        migrations.AddField(
            model_name='record',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, to='map.Person'),
        ),
    ]
