# Generated by Django 2.0.3 on 2018-04-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20180403_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, related_name='record', to='map.Person'),
        ),
    ]
